In [8]:
import numpy as np
a=np.array([545,84,84,51,4661,36])
b=np.array([5458,88,474,46,84,88])
print(a*b)

[2974610    7392   39816    2346  391524    3168]


In [4]:
a=[545,84,84,51,4661,36]
b=[5458,88,474,46,84,88]
print(a+b)

[545, 84, 84, 51, 4661, 36, 5458, 88, 474, 46, 84, 88]


In [16]:
import numpy as np
a=np.array([45,8,86,8,451,54])
print(a[::-1])

[ 54 451   8  86   8  45]


In [93]:
import numpy as np
a=np.array([[45,8,86,8],[54,848,18,48]])
print(np.shape(a))
print(np.size(a))
print(np.ndim(a))
print(a.dtype)
print(type(a))
print("\n\n\n\n")
print(a.astype(float))

(2, 4)
8
2
int32
<class 'numpy.ndarray'>





[[ 45.   8.  86.   8.]
 [ 54. 848.  18.  48.]]


In [85]:
a=[]
for i in range(0,2):
    b=input("enter")
    a.append(b)

print(a)

enter 45
enter 459


['45', '459']


In [ ]:
dictionary input

In [10]:
import numpy as np
a=np.array([545,84,84,51,4661,36])
b=np.array([5458,88,474,46,84,88])
print(np.add(a,b))
print(np.multiply(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))
print(np.power(a,b))
c=a.astype(float)
d=b.astype(float)
e=np.sqrt(c,d)
print(e,"hihi")
print(a%b)
      

[6003  172  558   97 4745  124]
[2974610    7392   39816    2346  391524    3168]
[-4913    -4  -390     5  4577   -52]
[ 0.09985343  0.95454545  0.17721519  1.10869565 55.48809524  0.40909091]
[2088219201          0          0 -852843303  658009073          0]
[23.34523506  9.16515139  9.16515139  7.14142843 68.27151675  6.        ] hihi
[545  84  84   5  41  36]


In [14]:
import numpy as np
a=np.array([545,84,84,51,4661,36])
b=np.array([5458,88,474,46,84,88])
print(np.concatenate([a,b]))

[ 545   84   84   51 4661   36 5458   88  474   46   84   88]


In [20]:
import numpy as np
a=np.array([545,84,84,51,4661,36])
b=np.array([5458,88,474,46,84,88])
print(np.concatenate([a,b],axis=0))



[ 545   84   84   51 4661   36 5458   88  474   46   84   88]


In [22]:
import numpy as np
a=np.array([545,84,84,51,4661,36])
b=np.array([5458,88,474,46,84,88])
print(np.hstack([a,b]))

[ 545   84   84   51 4661   36 5458   88  474   46   84   88]


In [24]:
import numpy as np
a=np.array([545,84,84,51,4661,36])
b=np.array([5458,88,474,46,84,88])
print(np.vstack([a,b]))

[[ 545   84   84   51 4661   36]
 [5458   88  474   46   84   88]]


In [30]:
import numpy as np
a=np.array([545,84,84,51,4661,36])
b=np.array([5458,88,474,46,84,88])
print(np.array_split(a,5))

[array([545,  84]), array([84]), array([51]), array([4661]), array([36])]


In [38]:
import numpy as np
a=np.array([545,84,84,51,4661,36])
b=np.array([5458,88,474,46,84,88])
print(np.append(a,[455,68,84]))
print(np.append(b,[455,68,84]))
print(np.insert(a,1,554))
print(np.delete(a,1))

[ 545   84   84   51 4661   36  455   68   84]
[5458   88  474   46   84   88  455   68   84]
[ 545  554   84   84   51 4661   36]
[ 545   84   51 4661   36]


In [50]:
import numpy as np
a=np.array([545,84,84,51,4661,36])
b=np.array([5458,88,474,46,84,88])
print(np.sort(a))
print(np.where(a%2==0))
bb=np.sort(a)
print(np.searchsorted(bb,51))

[  36   51   84   84  545 4661]
(array([1, 2, 5], dtype=int64),)
1


In [56]:
import numpy as np
a=np.array([45,8,5488,452])
fa=[True,True,False,True]
n=a[fa]
print(n)

[ 45   8 452]


In [58]:
import numpy as np
a=np.array([45,8,5488,452])
fa=a>50
n=a[fa]
print(n)

[5488  452]


In [2]:
import numpy as np
a=np.array([45,50,75,80])
b=np.array([50,45,080,75])
print(np.cumsum(a))
print(np.sum(a))
print(np.mean(a))

[  45   53 5541 5993]
5993
1498.25


In [6]:
import numpy as np
a=np.array([45,50,75,80])
b=np.array([50,45,80,75])
print(np.cumprod([a,b],axis=0))

[[  45   50   75   80]
 [2250 2250 6000 6000]]


In [18]:
import numpy as np
price=np.array([45,50,75,80])
quantity=np.array([50,45,80,75])
total=price*quantity
for i in range(0,4):
    print("the total for ",i+1,"is",total[i])
    

the total for  1 is 2250
the total for  2 is 2250
the total for  3 is 6000
the total for  4 is 6000


In [40]:
import numpy as np
import statistics as st
a=np.array([80,50,54,75,85])
b=np.array([85,48,80,47,95])
print(np.median(a))#central value after sorting
print(np.mean(a))
print(st.mode(a))#number that appears the most
print(np.std(a))#measure of how data is dispersed around the mean value
print(np.var(a))#square of std. deviation
print(np.corrcoef([a,b]))# relationship between two or more variables

75.0
68.8
80
14.133647795243801
199.76
[[1.        0.4976954]
 [0.4976954 1.       ]]


In [42]:
b=[45,8,484,684,4]
import numpy as np
c=np.array(b)
print(c)

[ 45   8 484 684   4]
